FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the rest of the application code
COPY ../ .

# Copy the requirements file first to leverage Docker cache
COPY ./requirements.txt ./requirements.txt

# Install the dependencies
RUN pip3 install -r requirements.txt


# Set the default command to run the application
# CMD ["python3", "/app/src/app.py"]